"""Produce a privacy-safe structural profile of the SoilSync soil CSV."""

from __future__ import annotations

import argparse
import csv
import hashlib
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CSV = ROOT / "soil_data_all.csv"
NUMERIC_FIELDS = (
    "soil_pH",
    "total_Nitrogen_percent_",
    "total_Org_Carbon_percent_",
    "phosphorus_Olsen_ppm",
    "potassium_meq_percent_",
)
COVERAGE_FIELDS = (
    "year",
    "county",
    "soil_depth_cm",
    *NUMERIC_FIELDS,
    "crop",
    "fertilizer_Recommendation",
    "latitude",
    "longitude",
    "final_Latitude",
    "final_Longitude",
)


def is_number(value: str) -> bool:
    """Accept ordinary dot-decimal numeric values, without coercing source text."""
    candidate = value.strip()
    return bool(candidate and re.fullmatch(r"[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?", candidate))


def profile_csv(csv_path: Path) -> dict[str, object]:
    present = Counter()
    invalid_numeric = Counter()
    depth_labels = Counter()
    county_labels = Counter()
    years: list[int] = []
    identifiers: set[str] = set()
    duplicate_ids = 0
    missing_ids = 0
    record_count = 0
    crop_count = 0
    recommendation_count = 0
    recommendation_texts: set[str] = set()
    original_coordinate_pairs = 0
    final_coordinate_pairs = 0

    with csv_path.open("r", encoding="utf-8-sig", newline="") as source:
        reader = csv.DictReader(source)
        columns = reader.fieldnames or []
        for row in reader:
            record_count += 1
            for field in COVERAGE_FIELDS:
                value = (row.get(field) or "").strip()
                if value:
                    present[field] += 1

            identifier = (row.get("id") or "").strip()
            if not identifier:
                missing_ids += 1
            elif identifier in identifiers:
                duplicate_ids += 1
            else:
                identifiers.add(identifier)

            for field in NUMERIC_FIELDS:
                value = (row.get(field) or "").strip()
                if value and not is_number(value):
                    invalid_numeric[field] += 1

            depth = (row.get("soil_depth_cm") or "").strip()
            if depth:
                depth_labels[depth] += 1

            county = (row.get("county") or "").strip()
            if county:
                county_labels[county.casefold()] += 1

            year = (row.get("year") or "").strip()
            if year.isdigit():
                years.append(int(year))

            crop = (row.get("crop") or "").strip()
            if crop:
                crop_count += 1

            recommendation = (row.get("fertilizer_Recommendation") or "").strip()
            if recommendation:
                recommendation_count += 1
                recommendation_texts.add(recommendation)

            if (row.get("latitude") or "").strip() and (row.get("longitude") or "").strip():
                original_coordinate_pairs += 1
            if (row.get("final_Latitude") or "").strip() and (row.get("final_Longitude") or "").strip():
                final_coordinate_pairs += 1

    digest = hashlib.sha256()
    with csv_path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)

    return {
        "path": csv_path.name,
        "bytes": csv_path.stat().st_size,
        "sha256": digest.hexdigest(),
        "columns": columns,
        "rows": record_count,
        "present": present,
        "invalid_numeric": invalid_numeric,
        "depth_labels": depth_labels,
        "county_labels": county_labels,
        "year_min": min(years) if years else None,
        "year_max": max(years) if years else None,
        "duplicate_ids": duplicate_ids,
        "missing_ids": missing_ids,
        "crop_count": crop_count,
        "recommendation_count": recommendation_count,
        "unique_recommendations": len(recommendation_texts),
        "original_coordinate_pairs": original_coordinate_pairs,
        "final_coordinate_pairs": final_coordinate_pairs,
    }


def percentage(count: int, total: int) -> str:
    if not total:
        return "0.0%"
    return f"{count / total * 100:.1f}%"


def render_report(profile: dict[str, object]) -> str:
    rows = int(profile["rows"])
    present = profile["present"]
    invalid_numeric = profile["invalid_numeric"]
    depth_labels = profile["depth_labels"]
    county_labels = profile["county_labels"]
    assert isinstance(present, Counter)
    assert isinstance(invalid_numeric, Counter)
    assert isinstance(depth_labels, Counter)
    assert isinstance(county_labels, Counter)

    lines = [
        "# Soil CSV Data Audit",
        "",
        "Generated by `python scripts/audit_soil_csv.py`. This report contains aggregate structural statistics only; it does not include farmer names, phone numbers, coordinates, or raw recommendation text.",
        "",
        "## Input Fingerprint",
        "",
        f"- File: `{profile['path']}`",
        f"- Size: {int(profile['bytes']):,} bytes",
        f"- SHA-256: `{profile['sha256']}`",
        f"- Rows: {rows:,}",
        f"- Columns: {len(profile['columns'])}",
        f"- Year range from valid `year` values: {profile['year_min']} to {profile['year_max']}",
        f"- Missing `id` values: {profile['missing_ids']}",
        f"- Duplicate non-empty `id` values after first occurrence: {profile['duplicate_ids']}",
        "",
        "## Core Field Coverage",
        "",
        "Coverage counts non-empty source cells. Invalid numeric tokens are reported separately and are not considered usable measurements.",
        "",
        "| Source field | Non-empty | Missing | Invalid numeric |",
        "| --- | ---: | ---: | ---: |",
    ]

    for field in ("year", "county", "soil_depth_cm", *NUMERIC_FIELDS, "crop", "fertilizer_Recommendation"):
        count = int(present[field])
        invalid = int(invalid_numeric[field]) if field in NUMERIC_FIELDS else 0
        lines.append(f"| `{field}` | {count:,} ({percentage(count, rows)}) | {rows - count:,} | {invalid:,} |")

    lines.extend(
        [
            "",
            "## Depth Labels",
            "",
            "The source column is named `soil_depth_cm`, but its values are not consistently numeric depths. Top values are listed by frequency; source labels are preserved verbatim.",
            "",
            "| Source depth label | Rows |",
            "| --- | ---: |",
        ]
    )
    for label, count in depth_labels.most_common(12):
        safe_label = label.replace("|", "\\|").replace("\n", " ")
        lines.append(f"| `{safe_label}` | {count:,} |")

    lines.extend(
        [
            "",
            "## Geography and Recommendation Coverage",
            "",
            f"- County labels after case-folding: {len(county_labels)}",
            f"- Rows with original latitude/longitude pairs: {int(profile['original_coordinate_pairs']):,} ({percentage(int(profile['original_coordinate_pairs']), rows)})",
            f"- Rows with final latitude/longitude pairs: {int(profile['final_coordinate_pairs']):,} ({percentage(int(profile['final_coordinate_pairs']), rows)})",
            f"- Rows with crop text: {int(profile['crop_count']):,} ({percentage(int(profile['crop_count']), rows)})",
            f"- Rows with fertilizer recommendation text: {int(profile['recommendation_count']):,} ({percentage(int(profile['recommendation_count']), rows)})",
            f"- Distinct non-empty recommendation strings: {int(profile['unique_recommendations']):,}",
            "",
            "## Import Decisions Required",
            "",
            "- Parse only validated numeric tokens. Keep invalid values as missing/unusable and record a rejection reason; never silently coerce text or decimal-comma values.",
            "- Preserve the original depth label. Do not infer centimeter ranges from `top`, `sub`, or combined labels without a source-backed mapping.",
            "- Keep latitude/longitude optional; do not use county centroids as farm coordinates.",
            "- Normalize county labels only through an approved administrative-area crosswalk; case-folding alone is not a county mapping.",
            "- Keep source recommendation text as provenance/reference material, not as a measured crop-response target.",
            "- Obtain agronomic review of units, methods, depth interpretation, and threshold rules before producing actionable advice.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV, help="Input CSV path (default: workspace soil_data_all.csv)")
    parser.add_argument("--output", type=Path, help="Write the report to this path (default: print to stdout)")
    arguments = parser.parse_args()

    profile = profile_csv(arguments.csv)
    report = render_report(profile)
    if arguments.output:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(report, encoding="utf-8")
        print(f"Wrote aggregate audit report to {arguments.output}")
    else:
        print(report)


if __name__ == "__main__":
    main()
